### ISSUE TITLE
coupled_diags not working

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_processflow#22]
In my most recent test (`/p/cscratch/acme/golaz1/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison/input/run.cfg`), coupled_diags simply will not run.

The status page reports:

`>   coupled_diags -- 0 JobStatus.WAITING_ON_INPUT`

I don't know how to tell which files the processflow is waiting for.

**Comment by sterlingbaldwin** [comment]
Update to the latest nightly build (v0.3.17) and run with the -f flag. This will print out a file_list.txt file into your output directory with the current state of the file_list every 10 seconds.

**Comment by mccoy20** [comment]
What's the update command again? I couldn't find it in the documentation, or do we need to do conda install again?

**Comment by golaz** [comment]
@mccoy20 , try

```
bash
source activate workflow
conda install -c acme/label/nightly processflow
```

To check which version of processflow is in your environment:

```
conda list processflow
```

**Comment by golaz** [comment]
I reran with the -f option and the resulting file_list.txt provided some useful info. The coupled_diags would not start because they were waiting on one file:

` 'MPAS_RST': {'mpaso.rst.0003-01-01_00000.nc': <SetStatus.NO_DATA: 0>},`

The file existed at the source, but for some reason it was not being transferred. I then manually transferred the missing file into its proper destination. At that point, coupled_diags for four year sets started, but they all failed very quickly.

**Comment by sterlingbaldwin** [comment]
```
rm: cannot remove `config.ocnice': Permission denied
Traceback (most recent call last):
  File "python/setup_ocnice_config.py", line 150, in <module>
    filePointer = open(outFileName, 'w')
IOError: [Errno 13] Permission denied: 'config.ocnice'
```

This looks like the internal config file that coupled_diags creates for themselves and then deletes. Because of the way they do this, every user writes out a config file to the same location, reads that file, and then deletes it. This means there's a race condition and only a single user on the machine can be running the coupled_diags at once (I filed a bug when them 4 months ago about this). This also means that all users must have write access to the coupled_diags code directory. Im going to have to change the whole directory to read/write/execute for everyone.

**Comment by sterlingbaldwin** [comment]
Supposedly this is being addressed in https://github.com/ACME-Climate/a-prime/pull/3

**Comment by milenaveneziani** [comment]
@sterlingbaldwin: we can actually remove the `coupled_diags` directory all together, because whatever we had in there now is part of the `a-prime` repo. I left it in there to make sure that everything worked in the new repo, but we have been running a-prime on its own for many months now, so I think that directory can be safely removed.
Pinging @kevans32 as well in case she is contrary to that idea.

**Comment by milenaveneziani** [comment]
Also, to reply to the config file issue for MPAS-Analysis: we now do things differently, in the sense that the set of config files that are used by a-prime to produce MPAS plots, are saved in a scratch output directory, not in the main a-prime directory. This was done prior to ACME-Climate/a-prime#3.

sorry that I didn't notice this issue being open before. Sometimes the github notifications are too many..

**Comment by milenaveneziani** [comment]
but so, is this new `acme_processflow` repository the old `PreAndPostProcessingScripts`?

**Comment by kevans32** [comment]
Wow yea- we moved that over to a-prime months ago. I am happy to remove it since we no longer use it, but the fact that it did not work for someone means someone does not know to use a-prime? All the more reason to remove it so its not used in error.

**Comment by milenaveneziani** [comment]
> but so, is this new acme_processflow repository the old PreAndPostProcessingScripts?

I can answer my own question. It is not. But then I guess I don't understand how the problem with `coupled_diags` showed up here. Is it because this code drives the stuff under `PreAndPostProcessingScripts`?

@kevans32: I don't think the intention of people running this is to run a-prime related stuff. For what I understand, that directory just got in the way somehow.

**Comment by sterlingbaldwin** [comment]
Ive been using the old coupled_diags from the PreAndPostProcessingScripts repo while I wait for the a-prime v1.0 PR to go through. This project launches a bunch of diagnostics, one of them being the couple_diags, but this will change over to a-prime once its merged. This issue shouldnt be related to anything @kevans32 or @milenaveneziani are doing.

**Comment by sterlingbaldwin** [comment]
Im waiting to switch to 1.0 since its close enough that I dont want to duplicate work.
