### ISSUE TITLE
Update acme_diags to v1

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_processflow#26]
Once @chengzhuzhang and @zshaheen give the green light, update acme_processflow to use acme_diags v1. (Can't wait to make use of it).

**Comment by golaz** [comment]
@sterlingbaldwin : do you have an estimate when you might be able to get this to work? I need to decide whether I should generate the figures by hand.

**Comment by zshaheen** [comment]
@chengzhuzhang and I are okay with Sterling integrating `acme_diags` into the processflow.

@sterlingbaldwin, to get the latest version in your env, do the following:
- `conda clean --all`: removes all downloaded Ananconda packages that were cached. This is because the new package is also `1.0.0` and otherwise, it won't get the latest one.
- `conda install acme_diags -c acme -c conda-forge -c uvcdat`: make sure you're getting `1.0.0` and not some older version.
- `conda install mesalib -c conda-forge -c uvcdat`: used for the `vcs` backend.

**Comment by sterlingbaldwin** [comment]
where there any changes from how users interact with it? Like any commandline arg changes, or changes to the parameter file?

**Comment by zshaheen** [comment]
From the version you were using, no. The only changes were how we handled colormaps, so nothing you really need to worry about.
