### ISSUE TITLE
'seasons' should not be required argument for [acme_diags]

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_processflow#40]
I don't think 'seasons'  should be a required argument for the configuration of [acme_diags].

**Comment by zshaheen** [comment]
This is kinda on our end.

Currently if the user does not define `seasons` in `acme_diags` (and thus the `acme_processflow`), `seasons=[]` and the diags aren't ran, since the first `for` loop loops through `seasons`.

We can edit [acme_parameter.py](https://github.com/ACME-Climate/acme_diags/blob/master/acme_diags/acme_parameter.py) to have `seasons=['ANN', 'DJF', 'MAM', 'JJA', 'SON']` by default. That should fix it. We have even release a 'bug' fix, `v1.0.1` once this and other issues are fixed.

**Comment by zshaheen** [comment]
@sterlingbaldwin To fix this on your end, if `seasons` is not defined, just set it to `['ANN', 'DJF', 'MAM', 'JJA', 'SON']`. This way, you don't have to wait for us to release a bugfix.
