### ISSUE TITLE
Running multiple instances of ncclimo fails

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_processflow#7]
This is probably more of an `acme1` issue rather than `acme_workflow`. 

Running multiple instances of `ncclimo` concurrently (either multiple year sets from one simulation, or year sets from multiple simulations) causes `ncclimo` to systematically fail.

Exact cause of failure varies, but error log include:

> OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
> OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 4134224 max

or

> libgomp: Thread creation failed: Resource temporarily unavailable

**Comment by golaz** [comment]
Wondering if @czender or @sterlingbaldwin have seen errors like this before?

**Comment by czender** [comment]
@doutriaux1 encountered a similar problem on 7/7/17. He closed the issue after saying 
"By playing with “ulimit –u ” we were able to bypass this.". Please try something along those lines. I am happy to add a line like that to ncclimo if necessary. Not sure if this issue is due to ncclimo though, or to the way NCO or other packages were put together in acme_workflow or something else... @sterlingbaldwin any suggestions?

**Comment by doutriaux1** [comment]
@sterlingbaldwin I think by default conda install an numpy that comes with openblas which is limited to 2 threads or something like that. try to remove the openblas package
```
conda remove openblas
```

**Comment by sterlingbaldwin** [comment]
I think its the openblas package, Ive had problems with it before.

**Comment by czender** [comment]
@cdoutriaux1 @golaz and @sterlingbaldwin To be clear, ncclimo is designed to run in multiple instances. The only exception is when it is run on the same input years but on different variables in different instances and the outputs are all stored in the same directory with the same names. That fails because the outputs overwrite eachother. The use-cases Chris mentions should work (presuming, of course, that the node has enough memory). The problems encountered with openblas seem to be due conda packaging, e.g., how conda packages openblas, and when NCO is installed through conda it can trigger this issue. When NCO is installed without conda it happily runs multiple instances (counterexamples welcome, I am unaware of any). Note that NCO depends on GSL and GSL is often built with gslcblas (e.g., RedHat, Debian) not openblas (Conda-forge). Pinging NCO conda-forge maintainer @ocefpaf to see if he is aware of any relevant openblas issues or solutions. Filipo, why does conda-forge GSL use openblas instead of gslcblas?

**Comment by czender** [comment]
@golaz I would welcome a minimal example that replicates the error messages you receive when running multiple instances of ncclimo

**Comment by doutriaux1** [comment]
@czender I concur this packaging of openblas with numpy by `conda-forge` is rather annoying, i wished it was off by default. Please feel free to include me in the conversation with @ocefpaf if needed.

**Comment by golaz** [comment]
@sterlingbaldwin : have you been able to reproduce the problem?

**Comment by czender** [comment]
@golaz and @sterlingbaldwin I am unsure what the exact use-case is here. Nevertheless, I've tested ncclimo with simultaneous runs and am unable to break it as long as I don't naively attempt to write to the same output file in multiple runs, or run out-of-memory (OOM). Memory usage and how to diagnose/avoid OOM conditions are described on the Confluence ncclimo page. An easy way to test simultaneous usage is to submit multiple invocations simultaneously and have them write to separate output files with the "-f fml_nm" option, using different family names for each invocation, e.g.,

ncclimo -p nil -f ncclimo1 -d 1 -c famipc5_ne30_v0.3_00003 -s 1980 -e 1983 -i ${DATA}/ne30/raw -o ${DATA}/ne30/clm -r ~zender/data/maps/map_ne30np4_to_fv129x256_aave.20150901.nc > ~/ncclimo.out1 2>&1 &
ncclimo -p nil -f ncclimo2 -d 1 -c famipc5_ne30_v0.3_00003 -s 1980 -e 1983 -i ${DATA}/ne30/raw -o ${DATA}/ne30/clm -r ~zender/data/maps/map_ne30np4_to_fv129x256_aave.20150901.nc > ~/ncclimo.out2 2>&1 &

If it is as fragile as Chris says then I suspect that is an unintended consequence of running in a different  environment (Python?) than I typically do. In that case, it should still be straightforward to isolate a series of commands that replicates the problem, capture their output, and send it all to me. Turning off the "oversubscribe" flag is, IMHO, at best a temporary solution until the root cause is diagnosed and fixed.

**Comment by sterlingbaldwin** [comment]
I think the issue is caused by the environment and isnt an ncclimo issue. My guess right now is that its hitting the default max process cap of 1024 and then failing to create new threads. I'll do a reboot tonight and the cap should be raised. Tomorrow I'll do a stress test.
